### ISSUE TITLE
How did you list only AUR packages?

### ISSUE THREAD

**Issue by rizzini** [ryukinix/dotfiles#9]
REF: https://github.com/ryukinix/dotfiles/blob/master/.pacman/aur.txt

Googling I found some Pacman commands, but they are not accurate. Thanks in advance and congrats on the repository. :)

**Comment by ryukinix** [comment]
I don't recall, sorry man. It has been a long time i did that. Somehow I made a command of pacman filtering as local installed (not available in the main repositories). I think you can find that, how filter them, at arch Linux forum.

**Comment by rizzini** [comment]
Thanks for replying, man.
